# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import configparser
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    api = ""
    secret = ""

    def showInfomation(self, msg):
        self.msginfo.setText(msg)

    def saveKey(self):
        curpath = os.path.dirname(os.path.realpath(sys.argv[0]))
        cfgpath = os.path.join(curpath, 'config.ini')
        conf = configparser.ConfigParser()
        if not conf.has_section("config"):
            conf.add_section("config")
        conf.set("config", "apikey", self.apikey.text())
        conf.set("config", "secretkey", self.seckey.text())
        with open(cfgpath, 'w') as configfile:
            conf.write(configfile)
            self.showInfomation('保存成功')

    def readkey(self):
        curpath = os.path.dirname(os.path.realpath(sys.argv[0]))
        cfgpath = os.path.join(curpath, 'config.ini')
        if not os.path.exists(cfgpath):
            self.msginfo.setText("请先设置APIKEY和SECRETKEY")
            return
        conf = configparser.ConfigParser()
        conf.read(cfgpath, encoding="utf-8")
        self.api = conf.get("config", "apikey")
        self.secret = conf.get("config", "secretkey")
        if self.api == "" or self.secret == "":
            self.msginfo.setText("提示", "请先设置APIKEY和SECRETKEY")
            return
        else:
            self.apikey.setText(self.api)
            self.seckey.setText(self.secret)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 479)
        MainWindow.setWindowIcon(QIcon(":/main.ico"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/back.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 40, 23, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background:#6C6C6C;\n"
"    color:white;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{                    \n"
"    background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 40, 23, 23))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background:#CE0000;\n"
"    color:white;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{                    \n"
"    background:#FF2D2D;\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid #3C3C3C!important;\n"
"    background:#AE0000;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 201, 20))
        self.label_2.setStyleSheet("QLabel{\n"
"color:black;\n"
"font-weight:bold;\n"
"font-family:\"微软雅黑\";\n"
"font-size:12pt\n"
"}")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(70, 70, 601, 321))
        self.tabWidget.setStyleSheet("#tab,#tab_2{\n"
"background:white;\n"
" border-radius:6px;\n"
"}\n"
"QTabWidget::pane{\n"
"    border:none;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"  left:5px;\n"
"}\n"
"QTabBar::tab{\n"
"  color:black;\n"
"  background:#F9FAFB;\n"
"  border-top-left-radius: 4px;\n"
"     border-top-right-radius: 4px;\n"
"     min-width: 60px;\n"
"     padding:5px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"\n"
"  background:#EDF6FB;\n"
" \n"
"}\n"
"QTabBar::tab:selected{\n"
"color:#06A8FF;    \n"
"background:#E0F2FB;\n"
"font-weight:bold;\n"
"}\n"
"QTabBar::tab:!selected{\n"
" margin-top:3px;\n"
"}\n"
"\n"
" ")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 601, 241))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 54, 12))
        self.label_5.setObjectName("label_5")
        self.per = QtWidgets.QComboBox(self.tab)
        self.per.setGeometry(QtCore.QRect(90, 256, 81, 22))
        self.per.setObjectName("per")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.per.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(180, 259, 41, 16))
        self.label_6.setObjectName("label_6")
        self.spd = QtWidgets.QSpinBox(self.tab)
        self.spd.setGeometry(QtCore.QRect(210, 257, 42, 22))
        self.spd.setMaximum(15)
        self.spd.setProperty("value", 5)
        self.spd.setObjectName("spd")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(270, 259, 41, 16))
        self.label_7.setObjectName("label_7")
        self.pit = QtWidgets.QSpinBox(self.tab)
        self.pit.setGeometry(QtCore.QRect(300, 257, 42, 22))
        self.pit.setMaximum(15)
        self.pit.setProperty("value", 5)
        self.pit.setObjectName("pit")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(350, 259, 41, 16))
        self.label_8.setObjectName("label_8")
        self.vol = QtWidgets.QSpinBox(self.tab)
        self.vol.setGeometry(QtCore.QRect(380, 257, 42, 22))
        self.vol.setMaximum(15)
        self.vol.setProperty("value", 5)
        self.vol.setObjectName("vol")
        self.convertbtn = QtWidgets.QPushButton(self.tab)
        self.convertbtn.setGeometry(QtCore.QRect(440, 257, 101, 23))
        self.convertbtn.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 7px;\n"
"    font-family:微软雅黑;\n"
"    background:#6633FF;\n"
"    border:1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#6666FF;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#6600FF;\n"
"}")
        self.convertbtn.setObjectName("convertbtn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setAutoFillBackground(False)
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(70, 80, 81, 16))
        self.label_4.setObjectName("label_4")
        self.apikey = QtWidgets.QLineEdit(self.tab_2)
        self.apikey.setGeometry(QtCore.QRect(160, 50, 251, 20))
        self.apikey.setObjectName("apikey")
        self.seckey = QtWidgets.QLineEdit(self.tab_2)
        self.seckey.setGeometry(QtCore.QRect(160, 80, 251, 20))
        self.seckey.setObjectName("seckey")
        self.savebtn = QtWidgets.QPushButton(self.tab_2)
        self.savebtn.setGeometry(QtCore.QRect(430, 50, 75, 51))
        self.savebtn.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 7px;\n"
"    font-family:微软雅黑;\n"
"    background:#6633FF;\n"
"    border:1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#6666FF;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#6600FF;\n"
"}")
        self.savebtn.setObjectName("savebtn")
        self.tabWidget.addTab(self.tab_2, "")
        self.msginfo = QtWidgets.QLabel(self.centralwidget)
        self.msginfo.setGeometry(QtCore.QRect(70, 390, 601, 16))
        self.msginfo.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"color: rgb(255, 0, 0);")
        self.msginfo.setText("")
        self.msginfo.setAlignment(QtCore.Qt.AlignCenter)
        self.msginfo.setObjectName("msginfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.readkey()
        self.savebtn.clicked.connect(self.saveKey)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "百度文本转语音-在线版"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "百度文字转语音-在线版"))
        self.label_5.setText(_translate("MainWindow", "发音人:"))
        self.per.setItemText(0, _translate("MainWindow", "度小美"))
        self.per.setItemText(1, _translate("MainWindow", "度小宇"))
        self.per.setItemText(2, _translate("MainWindow", "度逍遥"))
        self.per.setItemText(3, _translate("MainWindow", "度丫丫"))
        self.per.setItemText(4, _translate("MainWindow", "---精品语音库----"))
        self.per.setItemText(5, _translate("MainWindow", "度小鹿"))
        self.per.setItemText(6, _translate("MainWindow", "度博文"))
        self.per.setItemText(7, _translate("MainWindow", "度小童"))
        self.per.setItemText(8, _translate("MainWindow", "度小萌"))
        self.per.setItemText(9, _translate("MainWindow", "度米朵"))
        self.per.setItemText(10, _translate("MainWindow", "度小娇"))
        self.per.setItemText(11, _translate("MainWindow", "度逍遥"))
        self.label_6.setText(_translate("MainWindow", "语速:"))
        self.label_7.setText(_translate("MainWindow", "音调:"))
        self.label_8.setText(_translate("MainWindow", "音量:"))
        self.convertbtn.setText(_translate("MainWindow", "开始合成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "转语音"))
        self.label_3.setText(_translate("MainWindow", "API KEY:"))
        self.label_4.setText(_translate("MainWindow", "SECURITY KEY:"))
        self.savebtn.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "设置"))
import mainform_rc
